// Generated by npm run sync:assets — do not edit by hand
/** Root-relative URLs for files in public/assets/adverts/ */
export const ADVERT_URLS: readonly string[] = [
  "/assets/adverts/bookies.png",
  "/assets/adverts/Goblin_Market_002.jpg",
  "/assets/adverts/Goblin_Market_012.jpg",
  "/assets/adverts/Goblin_Market_032.jpg",
  "/assets/adverts/Goblin_Market_044.jpg",
  "/assets/adverts/keys.png",
  "/assets/adverts/MAP 2.jpg",
  "/assets/adverts/mmt.png",
  "/assets/adverts/motto.png",
  "/assets/adverts/tubs.png",
  "/assets/adverts/wanted.png"
];
