// Generated by npm run sync:assets — do not edit by hand
/** Root-relative URLs for files in public/assets/tv-float/ */
export const TV_FLOAT_URLS: readonly string[] = [
  "/assets/tv-float/500px-Goblin_Market_007.png",
  "/assets/tv-float/Goblin_Market_006.png",
  "/assets/tv-float/Goblin_Market_008.png",
  "/assets/tv-float/Goblin_Market_010.png",
  "/assets/tv-float/Goblin_Market_013.png",
  "/assets/tv-float/Goblin_Market_014.png",
  "/assets/tv-float/Goblin_Market_015.png",
  "/assets/tv-float/Goblin_Market_016.png",
  "/assets/tv-float/Goblin_Market_021.png",
  "/assets/tv-float/Goblin_Market_027.png",
  "/assets/tv-float/Goblin_Market_029.png",
  "/assets/tv-float/Goblin_Market_033.png",
  "/assets/tv-float/Goblin_Market_038.png",
  "/assets/tv-float/Goblin_Market_045.png"
];
